export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const ADD = 'ADD';
export const SUBSTRACT = 'SUBSTRACT';
export const STORE_RESULT = 'STORE_RESULT';
export const DELETE_RESULT = 'DELETE_RESULT';

export const GET_GRADES_CLASSES_INFO = 'GET_GRADES_CLASSES_INFO';
export const GET_CLASSES_INFO_BY_GRADEID = 'GET_CLASSES_INFO_BY_GRADEID';
export const TOGGLE_GRADE_TABLE_EDITING = 'TOGGLE_GRADE_TABLE_EDITING';
export const TOGGLE_CLASSES_TABLE_EDITING = 'TOGGLE_CLASSES_TABLE_EDITING';