export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const ADD = 'ADD';
export const SUBSTRACT = 'SUBSTRACT';
export const STORE_RESULT = 'STORE_RESULT';
export const DELETE_RESULT = 'DELETE_RESULT';

export const GET_GRADES_CLASSES_INFO = 'GET_GRADES_CLASSES_INFO';
export const GET_CLASSES_INFO_BY_GRADENUM = 'GET_CLASSES_INFO_BY_GRADENUM';
export const TOGGLE_GRADE_TABLE_EDITING = 'TOGGLE_GRADE_TABLE_EDITING';
export const TOGGLE_CLASSES_TABLE_EDITING = 'TOGGLE_CLASSES_TABLE_EDITING';

export const GET_STUDENTS = 'GET_STUDENTS';
export const GET_STUDENTS_BY_CLASSNUM = 'GET_STUDENTS_BY_CLASSNUM';
export const TOGGLE_STUDENTS_TABLE_EDITING = 'TOGGLE_STUDENTS_TABLE_EDITING';